#!/usr/bin/env python3
"""
Exult U7 English→Traditional Chinese Translation Tool
=====================================================
Reads Exult text message files (textmsg.txt), translates English text
to Traditional Chinese via OpenAI-compatible API, outputs patch-format results.

Usage:
  ── NVIDIA NIM (default) ──
    set NVIDIA_API_KEY=nvapi-...
    python translate_zh.py

  ── Local server (LM Studio, Ollama, vLLM, etc.) ──
    python translate_zh.py --base-url http://localhost:1234/v1 --api-key ""

  ── Other OpenAI-compatible API ──
    python translate_zh.py --base-url https://api.example.com/v1 --api-key sk-...

Options:
  --base FILE      Base textmsg.txt (default: ../content/bgkeyring/data/textmsg.txt)
  --patch FILE     Existing patch textmsg.txt to update (default: ../../ULTIMA7/patch/textmsg.txt)
  --api-key KEY    NVIDIA NIM API key (or env NVIDIA_API_KEY)
  --base-url URL   API endpoint (default: https://integrate.api.nvidia.com/v1)
  --model NAME     Model name (default: meta/llama-3.1-70b-instruct)
  --batch-size N   Texts per API call (default: 20)
  --skip-shapes    Skip shape names entirely
  --skip-msgs      Skip game messages entirely
  --skip-misc      Skip misc names entirely
  --min-shape N    Minimum shape ID to translate (skip terrain below this, default: 200)
  --dry-run        Show what would be translated without calling API
  --no-skip-names  Include proper names in translation (default: skip names)
"""

import argparse
import os
import re
import sys
import time
import json
from pathlib import Path
from typing import Dict, List, Optional, Tuple

# ── Configuration ──────────────────────────────────────────────────────────

SHAPE_SECTION = "shapes"
MSGS_SECTION = "msgs"
MISC_SECTION = "miscnames"

# Shape IDs below this threshold are considered terrain tiles (skip them).
DEFAULT_MIN_SHAPE = 200

# ── textmsg.txt Parser ────────────────────────────────────────────────────


def parse_textmsg(filepath: str) -> Dict[str, Dict[int, str]]:
    """
    Parse a textmsg.txt file into sections.
    Returns: { section_name: { index: value_string } }
    Both hex (0xNN) and decimal indices are supported.
    """
    sections: Dict[str, Dict[int, str]] = {}
    current_section: Dict[int, str] = {}
    current_name = "__global__"
    sections[current_name] = current_section

    if not os.path.exists(filepath):
        print(f"  [WARN] File not found: {filepath}")
        return sections

    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    for line_num, raw_line in enumerate(content.splitlines(), 1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue

        # Section start/end
        if line.lower().startswith("%%section"):
            parts = line.split(None, 1)
            name = parts[1].strip() if len(parts) > 1 else ""
            if name:
                current_name = name
                current_section = {}
                sections[current_name] = current_section
            continue
        if line.lower().startswith("%%endsection"):
            current_name = "__global__"
            current_section = sections.setdefault("__global__", {})
            continue

        # Parse "index:value"
        colon = line.find(":")
        if colon < 0:
            continue

        idx_str = line[:colon]
        value = line[colon + 1:]

        # Parse index (hex with 0x, or decimal)
        idx = None
        base = 10
        clean = idx_str.strip()
        if clean.startswith("0x") or clean.startswith("0X"):
            base = 16
            clean = clean[2:]
        try:
            idx = int(clean, base)
        except ValueError:
            print(f"  [WARN] Line {line_num}: invalid index '{idx_str}'")
            continue

        current_section[idx] = value

    return sections


def write_textmsg(
    sections: Dict[str, Dict[int, str]],
    filepath: str,
    *,
    existing_header: Optional[List[str]] = None,
) -> None:
    """
    Write sections to a patch-format textmsg.txt.
    Uses decimal indices (parser supports both hex and decimal).
    """
    with open(filepath, "w", encoding="utf-8", newline="\n") as f:
        # Write header comments if provided
        if existing_header:
            for h in existing_header:
                f.write(h + "\n")
        else:
            f.write("# Traditional Chinese (繁體中文) translations\n")
            f.write(f"# Generated by translate_zh.py\n")

        for section_name, entries in sections.items():
            if section_name == "__global__":
                # Write global entries first (outside any section)
                for idx in sorted(entries.keys()):
                    val = entries[idx]
                    f.write(f"{idx}:{val}\n")
                continue

            f.write(f"\n%%section {section_name}\n")
            for idx in sorted(entries.keys()):
                val = entries[idx]
                f.write(f"{idx}:{val}\n")
            f.write("%%endsection\n")


# ── LLM Translation ──────────────────────────────────────────────────────


def translate_batch(
    texts: List[Tuple[int, str]],
    api_key: str,
    base_url: str,
    model: str,
    source_type: str,
    max_retries: int = 3,
) -> List[Tuple[int, str]]:
    """
    Translate a batch of (index, english_text) pairs via OpenAI-compatible API.
    Returns: [(index, chinese_text), ...]
    """
    if not texts:
        return []

    try:
        from openai import OpenAI
    except ImportError:
        print("\n  ERROR: 'openai' package not installed. Run: pip install openai")
        sys.exit(1)

    client = OpenAI(api_key=api_key, base_url=base_url)

    # Build translation prompt
    text_block = "\n".join(f"[{i}] {t}" for i, t in texts)

    if source_type == "shapes":
        type_guide = (
            "These are object/character names shown when hovering over game elements. "
            "Be concise (1-4 characters preferred). Use standard gaming terminology."
        )
    elif source_type == "msgs":
        type_guide = (
            "These are game dialog lines, system messages, and UI labels. "
            "Preserve formatting characters like %s, %d, %1, %2, %3, %4, %5, %6, %7, %8, %9, "
            "\\n, and keep any leading/trailing spaces exactly as-is."
        )
    else:  # misc
        type_guide = (
            "These are item/object names with optional formatting (e.g. 'a/black pearl//s'). "
            "Translate the name parts but preserve the formatting symbols like / and //."
        )

    prompt = f"""You are a game localization expert. Translate the following English game text to Traditional Chinese (zh-TW).

{type_guide}

CRITICAL RULES:
1. Keep proper names (people, cities, places, character names, titles) in English — do NOT translate them
2. Preserve ALL formatting characters exactly: %s, %d, %1-%9, \\n, etc.
3. Preserve any leading/trailing whitespace exactly
4. Use natural, game-appropriate Traditional Chinese (Taiwan convention)
5. For object/item names, prefer concise translations (1-4 chars when possible)
6. Do NOT add extra commentary — just provide the translations

Format each line as:
[N] <translated text>

Text to translate:
{text_block}

Translations:"""

    for attempt in range(max_retries):
        try:
            response = client.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3,
                max_tokens=4000,
            )
            result = response.choices[0].message.content.strip()
            break
        except Exception as e:
            print(f"\n  [RETRY {attempt+1}/{max_retries}] API error: {e}")
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)
            else:
                print("  [ERROR] Giving up on this batch.")
                return [(idx, f"<<TRANSLATION_FAILED: {eng[:40]}>>") for idx, eng in texts]

    # Parse result
    parsed = {}
    for line in result.splitlines():
        line = line.strip()
        m = re.match(r'^\[(\d+)\]\s*(.*)', line)
        if m:
            idx = int(m.group(1))
            trans = m.group(2).strip()
            parsed[idx] = trans

    output = []
    for idx, eng in texts:
        if idx in parsed and parsed[idx]:
            output.append((idx, parsed[idx]))
        else:
            # Fallback: keep original (probably name that LLM chose to skip)
            output.append((idx, eng))

    return output


# ── Helpers ───────────────────────────────────────────────────────────────

def is_proper_name(name: str) -> bool:
    """
    Heuristic: check if the string looks like a proper name.
    Proper names: capitalized words that aren't common game terms.
    This is a rough filter; the LLM handles the actual decision.
    """
    # Single words that are always game items/objects
    common_terms = {
        "door", "chest", "wall", "floor", "ground", "water", "grass",
        "stone", "wood", "rock", "dirt", "sand", "carpet", "cave", "dungeon",
        "castle", "town", "house", "shop", "inn", "tavern", "temple", "shrine",
        "chair", "table", "bed", "desk", "drawer", "cupboard", "crate", "barrel",
        "bag", "pouch", "chest", "box", "candle", "torch", "lantern", "fireplace",
        "pot", "pan", "plate", "cup", "mug", "bottle", "flask", "vial", "potion",
        "scroll", "book", "map", "chart", "letter", "note", "sign", "board",
        "sword", "axe", "mace", "hammer", "bow", "arrow", "shield", "helmet",
        "armor", "mail", "plate", "leather", "boots", "gloves", "ring", "amulet",
        "gem", "jewel", "coin", "gold", "silver", "key", "lock", "trap", "lever",
        "button", "switch", "wheel", "rope", "chain", "ladder", "stairs", "bridge",
        "ship", "boat", "cart", "wagon", "anvil", "forge", "furnace", "oven",
        "loom", "spinning", "wheel", "mill", "press", "vice", "tool", "pick",
        "shovel", "hoe", "scythe", "sickle", "knife", "dagger", "spear", "staff",
        "wand", "orb", "crystal", "skull", "bone", "corpse", "remains", "ash",
        "dust", "dirt", "mud", "slime", "ooze", "jelly", "fungus", "mushroom",
        "plant", "flower", "bush", "tree", "log", "branch", "leaf", "vine",
        "weed", "thorn", "stalk", "reed", "crop", "grain", "wheat", "corn",
        "apple", "bread", "cheese", "meat", "fish", "egg", "milk", "wine", "ale",
        "beer", "food", "ration", "provision", "supply", "goods", "wares",
        "basket", "sack", "bale", "bundle", "pile", "stack", "heap", "mass",
        "statue", "pillar", "column", "arch", "window", "shutter", "rail", "fence",
        "gate", "portcullis", "bar", "cell", "cage", "tomb", "grave", "coffin",
        "altar", "pedestal", "cushion", "pillow", "blanket", "rug", "tapestry",
        "painting", "portrait", "mirror", "clock", "bell", "horn", "drum",
        "lute", "harp", "flute", "pipe", "whistle", "flag", "banner", "standard",
    }

    lower = name.strip().lower()
    if lower in common_terms:
        return False
    # If it looks like a proper noun (single capitalized word, not first word of phrase)
    words = lower.split()
    if len(words) <= 2:
        return False
    return False  # Let LLM handle it; this heuristic is only for pre-filtering


# ── Main ──────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Translate Exult U7 English text to Traditional Chinese via LLM.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    # File paths
    parser.add_argument(
        "--base",
        default=str(Path(__file__).resolve().parent.parent
                     / "content" / "bgkeyring" / "data" / "textmsg.txt"),
        help="Base game textmsg.txt",
    )
    parser.add_argument(
        "--patch",
        default=str(Path(__file__).resolve().parent.parent.parent
                     / "uc" / "ULTIMA7" / "patch" / "textmsg.txt"),
        help="Existing patch textmsg.txt to update",
    )
    # API — defaults to NVIDIA NIM
    parser.add_argument("--api-key", default=None,
                        help="API key (default: env NVIDIA_API_KEY; pass \"\" for local servers)")
    parser.add_argument(
        "--base-url",
        default="https://integrate.api.nvidia.com/v1",
        help="OpenAI-compatible endpoint (default: NVIDIA NIM; "
             "use http://localhost:1234/v1 for LM Studio / Ollama)",
    )
    parser.add_argument(
        "--model",
        default="meta/llama-3.1-70b-instruct",
        help="Model name (default: meta/llama-3.1-70b-instruct)",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        default=20,
        help="Texts per API call (default: 20)",
    )
    # Controls
    parser.add_argument("--skip-shapes", action="store_true", help="Skip shape names")
    parser.add_argument("--skip-msgs", action="store_true", help="Skip game messages")
    parser.add_argument("--skip-misc", action="store_true", help="Skip misc names")
    parser.add_argument(
        "--min-shape",
        type=int,
        default=DEFAULT_MIN_SHAPE,
        help=f"Minimum shape ID to translate (default: {DEFAULT_MIN_SHAPE})",
    )
    parser.add_argument("--dry-run", action="store_true", help="Dry run (no API calls)")
    parser.add_argument(
        "--no-skip-names",
        action="store_true",
        help="Include proper names in translation",
    )

    args = parser.parse_args()

    # API key — allow empty string for local servers with no auth
    api_key = os.environ.get("NVIDIA_API_KEY") if args.api_key is None else args.api_key
    if api_key is None and not args.dry_run:
        print("ERROR: No API key. Set NVIDIA_API_KEY env var, use --api-key, or pass --api-key \"\" for local servers")
        sys.exit(1)

    # ── Parse input files ─────────────────────────────────────────────
    print("=" * 60)
    print("Exult U7 Chinese Translation Tool")
    print("=" * 60)

    base_path = os.path.abspath(args.base)
    patch_path = os.path.abspath(args.patch)

    print(f"\nBase game text:  {base_path}")
    print(f"Patch file:      {patch_path}")
    print(f"Model:           {args.model}")
    print(f"Batch size:      {args.batch_size}")
    print()

    base_sections = parse_textmsg(base_path)
    patch_sections = parse_textmsg(patch_path)

    # ── Determine what needs translation ──────────────────────────────
    to_translate: Dict[str, List[Tuple[int, str]]] = {}

    section_names = []
    if not args.skip_shapes:
        section_names.append(SHAPE_SECTION)
    if not args.skip_msgs:
        section_names.append(MSGS_SECTION)
    if not args.skip_misc:
        section_names.append(MISC_SECTION)

    for sec in section_names:
        base_entries = base_sections.get(sec, {})
        patch_entries = patch_sections.get(sec, {})

        entries: List[Tuple[int, str]] = []
        for idx in sorted(base_entries.keys()):
            eng = base_entries[idx].strip()

            # Skip empty
            if not eng:
                continue

            # Skip already translated
            if idx in patch_entries:
                chk = patch_entries[idx].strip()
                if chk and chk != eng:
                    # Already has a different (Chinese) translation
                    continue

            # For shapes: skip terrain/low IDs
            if sec == SHAPE_SECTION and idx < args.min_shape:
                continue

            # Remove surrounding quotes for cleaner display
            display_eng = eng.strip('"').strip()

            # Skip single chars, numbers, or very short fragments
            if len(display_eng) <= 1 and not display_eng.isalpha():
                continue

            entries.append((idx, eng))

        if entries:
            to_translate[sec] = entries

    # ── Summary ────────────────────────────────────────────────────────
    total = sum(len(v) for v in to_translate.values())
    print(f"\nTranslation needs:")
    for sec, entries in to_translate.items():
        print(f"  {sec:12s}: {len(entries):5d} entries")
    print(f"  {'TOTAL':12s}: {total:5d} entries\n")

    if total == 0:
        print("Nothing to translate. All entries appear to be already translated.")
        return

    if args.dry_run:
        print("DRY RUN — no API calls made.")
        for sec, entries in to_translate.items():
            print(f"\n  [{sec}] First 5 untranslated entries:")
            for idx, eng in entries[:5]:
                print(f"    {idx}: {eng.strip('"')[:60]}")
            if len(entries) > 5:
                print(f"    ... and {len(entries) - 5} more")
        return

    # ── Translate ──────────────────────────────────────────────────────
    for sec, entries in to_translate.items():
        print(f"\n─── Translating [{sec}] ({len(entries)} entries) ───")

        # Split into batches
        batch_size = args.batch_size
        all_results: List[Tuple[int, str]] = []

        for batch_start in range(0, len(entries), batch_size):
            batch = entries[batch_start:batch_start + batch_size]
            batch_num = batch_start // batch_size + 1
            total_batches = (len(entries) + batch_size - 1) // batch_size

            # Strip quotes from English text for cleaner display
            clean_batch = [
                (i, t.strip('"')) for i, t in batch
            ]

            print(f"  Batch {batch_num}/{total_batches} ({len(batch)} texts)...", end="", flush=True)

            results = translate_batch(
                clean_batch,
                api_key,
                args.base_url,
                args.model,
                sec,
            )
            all_results.extend(results)

            # Check for names the LLM chose to skip (returned same text)
            kept_english = 0
            for idx, trans in results:
                original = dict(clean_batch)[idx]
                if trans.strip() == original.strip():
                    kept_english += 1

            if kept_english > 0:
                print(f" done ({kept_english} kept as English names)")
            else:
                print(" done")

            # Avoid rate limiting
            if batch_start + batch_size < len(entries):
                time.sleep(0.5)

        # ── Update patch section ───────────────────────────────────────
        patch_sec = patch_sections.setdefault(sec, {})
        for idx, trans in all_results:
            patch_sec[idx] = trans

    # ── Write patch file ──────────────────────────────────────────────
    # Preserve existing comments at top of patch file
    existing_header = None
    if os.path.exists(patch_path):
        with open(patch_path, "r", encoding="utf-8", errors="replace") as f:
            lines = f.readlines()
        header_lines = []
        for line in lines:
            if line.startswith("#"):
                header_lines.append(line.rstrip("\n\r"))
            else:
                break
        if header_lines:
            existing_header = header_lines

    # Also merge back any existing translations that weren't touched
    # (we already built patch_sections from current patch file)
    write_textmsg(patch_sections, patch_path, existing_header=existing_header)

    print(f"\n✅ Translations written to: {patch_path}")
    print(f"   Total entries translated: {total}")

    # Stats per section
    for sec in section_names:
        base_count = len(base_sections.get(sec, {}))
        patch_count = len(patch_sections.get(sec, {}))
        pct = (patch_count / base_count * 100) if base_count > 0 else 0
        print(f"   {sec}: {patch_count}/{base_count} ({pct:.0f}%)")


if __name__ == "__main__":
    main()
